### ISSUE TITLE
Packages needed for all supported delphi versions

### ISSUE THREAD

**Issue by kattunga** [kattunga/IWBootstrapFramework#1]
We need to create packages for all supported delphi versions

**Comment by tdzieciol** [comment]
I made packages for Delphi XE6, XE8 and D10 Seattle. You can find them on my fork.

**Comment by kattunga** [comment]
Please make a pull request so i can check them and commit.

El 8 de octubre de 2015 1:52:35 PM GMT-03:00, tdzieciol notifications@github.com escribió:

> I made packages for Delphi XE6, XE8 and D10 Seattle. You can find them
> on my fork.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kattunga/IWBootstrapFramework/issues/1#issuecomment-146620069

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kattunga** [comment]
thank you.
