### ISSUE TITLE
Bug in TIWBSMemo - Text property in modal frame returns empty string

### ISSUE THREAD

**Issue by tdzieciol** [kattunga/IWBootstrapFramework#11]
TIWBSMemo is used on frame showed as modal (IWBSModal). In async events (Button.OnAsyncClick) Text property always returns empty string. WIth TIWBSInput component its works OK.
Sample project http://www.ktsoft.pl/download/Project3.zip

**Comment by kattunga** [comment]
I fixed this two days ago. Download latest commit and replace iwbs.js in you wwwroot directory.
I added your example in demo/IWBSSimpleTest folder

**Comment by tdzieciol** [comment]
Yes, now its work ok. 
I did not find the description of this fix in the commit log.
Thanks.

**Comment by kattunga** [comment]
Yes. I'm doing so many changes that I forget to comment some fixes.
