### ISSUE TITLE
IDE error when click on Region

### ISSUE THREAD

**Issue by raelb** [kattunga/IWBootstrapFramework#15]
Hi,

I open the IWBSDemo, and go to Unit2.pas. When I click on the region, somewhere below the layout manager I get this error:

exception class    : EConvertError
exception message  : '' is not a valid integer value.

MadExcept report:

main thread ($8b4):
500901f5 +019 rtl180.bpl            System.SysUtils     5325   +1 ConvertErrorFmt
50091f44 +02c rtl180.bpl            System.SysUtils     7973   +2 StrToInt
35713280 +288 dclIWBootstrapXE4.bpl Iwbsregister                  TIWBSPaintHandlerCustomInput.Paint
19d9d55f +017 Intraweb_14_DXE4.bpl  Iwbasecontrol                 TIWBaseControl.Paint
19dee0b6 +002 Intraweb_14_DXE4.bpl  Iwvclbasecontrol              TIWVCLBaseControl.IWPaint
19dee128 +068 Intraweb_14_DXE4.bpl  Iwvclbasecontrol              TIWVCLBaseControl.WMPaint
50452af9 +2bd vcl180.bpl            Vcl.Controls        7224  +91 TControl.WndProc
50452734 +024 vcl180.bpl            Vcl.Controls        7002  +10 TControl.Perform
50457a62 +18e vcl180.bpl            Vcl.Controls       10197  +27 TWinControl.PaintControls
5045785d +131 vcl180.bpl            Vcl.Controls       10143  +24 TWinControl.PaintHandler
50457f74 +048 vcl180.bpl            Vcl.Controls       10324   +6 TWinControl.WMPaint
19d9827a +012 Intraweb_14_DXE4.bpl  Iwvclbasecontainer            TIWBaseContainer.WMPaint

I am using Delphi XE4.

Image:
![iwbs_ide_click_in_region_error](https://cloud.githubusercontent.com/assets/13108198/10944631/da44c46c-8322-11e5-83ea-1aad955d2fd9.png)

After the error occurs, If I click on a region (e.g. IWBSRegion2) then the entire region sticks to the mouse, and follows where ever I move the mouse. There is no way to let go of the region. (other than to just close the form). This seems to be a side-effect of the above mentioned error.

Image:
![iwbs_ide_click_in_left_region_issue](https://cloud.githubusercontent.com/assets/13108198/10944939/2a6599f2-8324-11e5-9e9f-e20a52e6a1ac.png)

**Comment by kattunga** [comment]
Yes. I lost glyphicon.res in my last commit.
It should be fixed now. Build and install design package again and let me know if it is fixed for you.

**Comment by raelb** [comment]
Yes, it's fixed now. Thanks
