### ISSUE TITLE
TIWBSImage and absolute image path

### ISSUE THREAD

**Issue by robertonicchi** [kattunga/IWBootstrapFramework#16]
For coherence to the TIWImageFile behaviour would better if the image path (imagefile property) is automatically changed from absolute to relative in the generated html code.
The advantage of ImageFile with absolute path over imagesrc is that it gives a design time preview of the image.
Consider this anyway a very secondary request that is not essential.

**Comment by kattunga** [comment]
Fixed in latest commit
