### ISSUE TITLE
Symptom that may indicate a problem.

### ISSUE THREAD

**Issue by robertonicchi** [kattunga/IWBootstrapFramework#17]
When refreshing a page (F5) where a Tiwbstabcontrol is present the activetab is reset to the default one (the tab that was set at design time or set in the oncreate event of the form).

If a modal dialog is opened (for example using webapplication.ShowMessage or a Tframe) then the active tab won't be changed anymore doing a page refresh.

**Comment by kattunga** [comment]
That is the designed behavior.
Selected page is reported to served side on any async call.
If you need to keep your selected page always in sync with the server you can simple set the OnAsyncChange event of the tab with an empty code:

``` pascal
procedure TIWForm2.IWTabControl21AsyncChange(Sender: TObject;
  EventParams: TStringList);
begin
  //
end;
```

This will force to submit any page change to the server.
Note that this will impact on performance on slow connections.
This is why is not enabled by default.

Regards
