### ISSUE TITLE
Multi column images grid

### ISSUE THREAD

**Issue by robertonicchi** [kattunga/IWBootstrapFramework#20]
I think could be very useful a component to show images (together with others component like text, buttons, checkbox, etc ....) in a responsive multi column grid.

I mean something like this: https://github.com/michaelsoriano/bootstrap-photo-gallery
or this: http://alijafarian.com/demos/responsive-image-grids-using-css/

I know it's possible to use external bootstrap addons but a dedicated Delphi component maybe could makes things easier :)

I'm thinking to a typical electronic commerce's application where the user choose products from a multi column grid and adds it to a basket.

thanks

**Comment by kattunga** [comment]
This scope of this framework is to has a basic set of components that could be easily extended by users.
This is was I call a core framework.
My objectives for this framework is to be rock solid, bugs free and best performance.
I have no time to maintain a larger project. 
So unfortunately, this project will not have components to wrap third party plugins.
Users are welcome to create their own projects to extend this framework.

Regards
