### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by robertonicchi** [kattunga/IWBootstrapFramework#21]
The file dclIWBootStrapXE6.dres is missing recompiling dclIWBootstrapXE6.bpl

**Comment by kattunga** [comment]
That file is not part of sources.
It is automatically generated when you open and build dclIWBootstrapXE6.dpk.
I don't know what could be the problem.

**Comment by robertonicchi** [comment]
I see that in the project source is present {$R *.dres}
Removing it fix the compiling error.

**Comment by kattunga** [comment]
And you still see glyphicons on buttons at design time?

**Comment by robertonicchi** [comment]
At design time i can't see glyphicons. I see a small square box.
If i don't remove {$R *.dres} and i get the .dres file from an older version where it was present, i still can't see the icons at design time
For IWBSDropDown component too i can't see at design time the correct icon; i see the squared box.
Anyway at runtime i can see always the icons.

**Comment by kattunga** [comment]
Please, check latest commit.

on top of dclIWBootstrapXE6.dpk you should only see:

``` pascal
package dclIWBootstrapXE6;

{$R 'glyphicons.res' 'glyphicons.RC'}

{$IFDEF IMPLICITBUILDING This IFDEF should not be used by users}
...
```

**Comment by robertonicchi** [comment]
Now the package compile (and install) without problems.
Anyway at design time i still can't see the glyph icons. At runtime yes.

**Comment by kattunga** [comment]
Please, test latest commit.
I completely replace glyphicon res file with a const.
There should be no more problem.

**Comment by robertonicchi** [comment]
Thanks, now is working fine.
