### ISSUE TITLE
Changing TIWBSTabControl activepage by code

### ISSUE THREAD

**Issue by robertonicchi** [kattunga/IWBootstrapFramework#23]
In a page of the iwbstabcontrol i have a label that has the onasyncclick event defined; it changes the activepage.

  menu_tab.ActivePage:=5;

The first time this works but if i click again it has no effects.

thanks

**Comment by kattunga** [comment]
Please check latest commit

**Comment by robertonicchi** [comment]
it's ok now. thanks.
