### ISSUE TITLE
IWBootStrap and cgdevtools Grid

### ISSUE THREAD

**Issue by titelivebe** [kattunga/IWBootstrapFramework#25]
Hi, 

I'm working with delphi 10 Seattle. I've an intraweb application with iwbootstrap. I want to link a iwcgjqgrid into the project but I can't have bootstrap style in my grid.

What can I do to have it?

Thanks by advance

**Comment by jerrivaldo** [comment]
Desculpe amigo, eu não uso esses componentes.

Em 05/04/2016 06:20, TiteLive escreveu:

**Comment by kattunga** [comment]
Hi, this is a CgDevTools issue, not an IWBootstrap issue.
jqGrid support bootstrap styles from version 5.0.
Take a look to IWBootStrap demo, there is an example with jqGrid 5.0.

I think that iwcgjqgrid is using an older jqGrid version.
You should ask about this in CgDevTools forum.

Regards
