### ISSUE TITLE
Does not compile with IW 14.1

### ISSUE THREAD

**Issue by michaschumann** [kattunga/IWBootstrapFramework#27]
Obviously a lot of reorganization has been made with Intraweb 14.1, some methods are private instead of protected and cannot be accessed in classes derived by IWBootstrap.

**Comment by michaschumann** [comment]
As it is easy to go back to Intraweb 14.0.63 just by installing this version over 14.1 there should be no pressure on fixing the issues.

**Comment by khemebuen** [comment]
Do you have an archive for IW 14.0.63 cannot find it on atozed site

**Comment by michaschumann** [comment]
Please ask Atozed - I don't want to run into license issues.

Herzliche Grüße – Kind regards
Michael Schumann, Dipl.-Ing. (FH)
http://itc-ms.de
Tel.  +49 6421 948 0430
Fax  +49 6421 948 0431

------ Originalnachricht ------
Von: "khemebuen" notifications@github.com
An: "kattunga/IWBootstrapFramework" 
IWBootstrapFramework@noreply.github.com
Cc: "michaschumann" ms@itc-ms.de; "Author" author@noreply.github.com
Gesendet: 23.11.2016 07:21:03
Betreff: Re: [kattunga/IWBootstrapFramework] Does not compile with IW 
14.1 (#27)

**Comment by loufeliz** [comment]
http://downloads.atozed.com/intraweb/iw14.0.63.exe

**Comment by kattunga** [comment]
Fixed in latest beta

**Comment by michaschumann** [comment]
Great work. I wish I could work with professional people like you in my day to day work! In Germany many people hide behind rules to protect them from doing their job and move forward. Thank god IT and my job is international...
