### ISSUE TITLE
An unhandled application error has occured within MyApp

### ISSUE THREAD

**Issue by fredycc** [kattunga/IWBootstrapFramework#29]
Hi, I think it's a fantastic framework.

I have installed v2.0beta3 & iw14.1.1 on Berlin Upd 2, all components were installed without problem. IWBSDemo compile and run. But when I access the URL a exception are display on browser.

> Application Error
An unhandled application error has occured within MyApp
Error message: Access violation at address 00000000007C7600 in module 'IWBSDemo.exe'. Read of address 0000000000000020
Depending on the error condition, it might be possible to restart the application. 

I attach the complete error message. 

Content & Application path are correct, I'm not sure what to do.

Thanks

[MyApp.zip](https://github.com/kattunga/IWBootstrapFramework/files/625313/MyApp.zip)

**Comment by kattunga** [comment]
I can't reproduce this issue.
Is anybody having the same issue?

**Comment by fredycc** [comment]
With v2.0beta4 + intraweb14.1.2 the bug has gone.

Thank you
