### ISSUE TITLE
Issue with grid system at runtime

### ISSUE THREAD

**Issue by mtaki14** [kattunga/IWBootstrapFramework#30]
I am having a strange issue where the grid columns do not appear in the place where they are supposed to be.

![bds_2016-12-27_08-50-05](https://cloud.githubusercontent.com/assets/7987430/21493024/d97c008e-cc11-11e6-8985-874c3a538aeb.png)

![bds_2016-12-27_08-49-50](https://cloud.githubusercontent.com/assets/7987430/21493025/e0052868-cc11-11e6-8bbf-be62900206f3.png)

As you can see, that although IWBSR2Right is supposed to be a sibling of IWBSR2Left, at runtime it appears as its child. 

Any idea why that may be?

**Comment by mtaki14** [comment]
I am having several issues like this one in various forms.

**Comment by robertonicchi** [comment]
Hello, i'm not very expert with Bootstrap but the max number of columns is 12. In your html code i see 6 * 3 = 18 columns. So the third column will start a new row.
Maybe this is the problem you are seeing ?
Roberto

**Comment by mtaki14** [comment]
What you say is correct, a bootstrap grid is made up of 12 columns. And for some reason I end up with 3 siblings with 6 column spaces which is not what I have at design time.

This screenshot should better show what I have at design time:

![bds_2016-12-27_12-24-44](https://cloud.githubusercontent.com/assets/7987430/21497708/9609c6ce-cc2f-11e6-8d86-ed00cba56f07.png)

...as opposed to what happens in the browser

![bds_2016-12-27_12-23-20](https://cloud.githubusercontent.com/assets/7987430/21497718/a7f5c48c-cc2f-11e6-9056-98e42e57d21d.png)

As you can see this is really strange. For some reason rows 3 and 4 appear **inside** row 2 although this is clearly not the case at design time.

**Comment by kattunga** [comment]
Please attach a test case so I can compile and debug it.

**Comment by mtaki14** [comment]
Hi, sorry for not getting back to you earlier but I got caught up in other work.

Here's a simple project with 1 form where the issue happens for me.


[TestProject.zip](https://github.com/kattunga/IWBootstrapFramework/files/716088/TestProject.zip)


The divs "IWBSROW3" and "IWBSROW4" appear as a children of "IWBSROW2" at runtime although at design time you can see they are supposed to be siblings.

**Comment by mtaki14** [comment]
Maybe I am doing something entirely wrong so please let me know if that is the case.

**Comment by kattunga** [comment]
mtaki,

The problem is that Html in IWBSRegion12 is malformed, you forgot to close the second div element.
You need to be very carefull when you include raw HTML inside divs.
I don't understand why you use all that raw HTML instead of using IWBoostrap components.

Regards

**Comment by mtaki14** [comment]
Thanks for the reply and for figuring out my mistake. 

The reason I was using so much raw html was because 1. I was simply experimenting with raw html and how it interacted with the components 2. If I remember correctly I was having some trouble making the labels appear on top of textboxes. I think I figured it out in the end but some of the previous forms with raw html were left behind.

Thanks again for your help.
