### ISSUE TITLE
Compiler error with Intraweb Version 14.1.16

### ISSUE THREAD

**Issue by NickHodges** [kattunga/IWBootstrapFramework#33]
When I compile a simple application (a TIWBSbutton and a TIWBSLabel) I get the following compiler error

[dcc32 Error] IWBSRestServer.pas(14): E2037 Declaration of 'Execute' differs from previous declaration

Steps to reproduce:

1.  Install IntraWeb 14.1.16
2.  Create new intraweb application using default settings
3.  Drop a TIWBSButton and a TIWBSLabel on the main form
4.  Press Compile

Expected:  Application runs
Actual: Compiler error

**Comment by kattunga** [comment]
Hi Nick,

Today I upgrade to 14.1.6 (I was using 14.1.3) and I did exactly your steps in order, by I didn't get a compiler error.

I check IW.Content.Base.pas:

```pascal
  TContentBase = class(TObject)
  protected
...
    function Execute(aRequest: THttpRequest; aReply: THttpReply; const aPathname: string;
                    aSession: TIWApplication; aParams: TStrings): Boolean; virtual; abstract;
...
```

and I don't find any diference with the TIWBSRestServer redeclaration.
```pascal
  TIWBSRestServer = class(TContentBase)
  protected
    function Execute(aRequest: THttpRequest; aReply: THttpReply; const aPathname: string; 
                    aSession: TIWApplication; aParams: TStrings): Boolean; override;
```

May be you keep old files of a previows IW version in you path?

**Comment by NickHodges** [comment]
That's entirely possible. I'll give it another try, after scouring for old DCU files.
